---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        exclude_types:
          - jpeg
          - png
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt-src
        args: [-w, -i, "2"]
  - repo: local
    hooks:
      - id: lint-repo
        name: lint-repo
        language: script
        entry: /bin/bash -c 'task lint'
      # - id: check-profiles
      #   name: check-profiles
      #   language: script
      #   entry: /bin/bash -c 'task check'
