---
version: '3.42.1'

vars:
  INSPEC_COMPOSE_SERVICE: chef/inspec:5.22.76
  INSPEC_PROFILES: ['ansible-baseline']

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose up cleanup
      - docker compose down --remove-orphans

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for:
          matrix:
            LINTER: ['yaml', 'workflows', 'filenames', 'folders'] #, 'markdown-links']
        cmd: docker compose up lint-{{.ITEM.LINTER}} --exit-code-from lint-{{.ITEM.LINTER}}

  check:
    desc: 'Check all Inspec profiles'
    cmds:
      - for:
          matrix:
            PROFILE: ['linux-essentials']
        cmd: docker compose up check-profile-{{.ITEM.PROFILE}} --exit-code-from check-profile-{{.ITEM.PROFILE}}

  # ===============================================================================================

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - docker compose up docs-dev-server
