---
version: '3.42.1'

dotenv: ['.env']

vars:
  INSPEC_COMPOSE_SERVICE: chef/inspec:5.22.76
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  cleanup:filesystem:
    desc: Cleanup the filesystem for this project
    cmds:
      - rm -rf .cache
      - rm -rf node_modules
      - rm -rf target
      - sudo rm -rf .devcontainer/ops
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +

  cleanup:
    desc: Cleanup the development environment for this project
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - task: cleanup:filesystem

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - task: cleanup:filesystem
      - for: ['yaml', 'filenames', 'folders', 'workflows', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  check:
    desc: 'Check all Inspec profiles'
    cmds:
      - for: ['container-essentials', 'linux-essentials', 'ollama-essentials']
        cmd: docker compose up check-profile-{{ .ITEM }} --exit-code-from check-profile-{{ .ITEM }}

  # ===============================================================================================

  copilot:lint-and-fix:
    desc: 'Use GitHub Copilot to lint and fix issues in the project'
    cmds:
      - task: cleanup
      - copilot --allow-all --prompt "/lint-and-fix"

  copilot:pull-request:
    desc: 'Use GitHub Copilot to create or update a pull request with a summary of all changes based on commit messages'
    cmds:
      - copilot --allow-all --prompt "/create-or-update-pull-request"
