---
name: "Pipeline: Release"

on:
  release:
    types: [created]

jobs:

  update-release-notes:
    uses: sommerfeld-io/.github/.github/workflows/release.yml@main
    permissions:
      contents: write
