---
name: "Pipeline: Release"

on:
  release:
    types: [created]

jobs:

  update-release-notes:
    uses: sommerfeld-io/.github/.github/workflows/release.yml@main
    secrets:
      COPILOT_CLI_TOKEN: ${{ secrets.COPILOT_CLI_TOKEN }}
    permissions:
      contents: write
      models: read
